### PR TITLE
Neighbor time output

### PR DESCRIPTION
**Pull request by streeve**

### CODE REVIEW

**Comment by pabloseleson** [comment]
@streeve : It seems this PR does two things:
(1) Outputs the neighbor time
(2) Splits "other_time" into "energy_time", "neighbor_time", and "output_time"
Is that correct?

**Comment by streeve** [comment]
> It seems this PR does two things: (1) Outputs the neighbor time (2) Splits "other_time" into "energy_time", "neighbor_time", and "output_time" Is that correct?

That's correct

**Comment by streeve** [comment]
> I just tried running ./ElasticWave using this branch and got the following error:

You need the input file

**Comment by pabloseleson** [comment]
Thanks, it is running.

From: Sam Reeve ***@***.***>
Date: Tuesday, January 16, 2024 at 12:16 PM
To: ORNL/CabanaPD ***@***.***>
Cc: Seleson, Pablo ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [ORNL/CabanaPD] Neighbor time output (PR #74)

I just tried running ./ElasticWave using this branch and got the following error:

You need the input file

**Review by pabloseleson — APPROVED** [review]

**Pull request merged**
